name: test_app
description: A test Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  meta: ^1.9.1
  provider: ^6.0.5
  solid_lints: ^0.0.19

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


